const $=s=>document.querySelector(s),root=document.documentElement,video=$('#camera'),canvas=$('#fx'),ctx=canvas.getContext('2d');
let w,h,dpr,target=0,current=0,index=0,startX=0,tracking=false,landmarker,particles=[];
const imgs=['https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1800&q=85','https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1800&q=85','https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=1800&q=85'];
function resize(){dpr=Math.min(devicePixelRatio||1,2);w=innerWidth;h=innerHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}
function setSlides(dir){index=(index+dir+imgs.length)%imgs.length;$('.current').style.backgroundImage='url("'+imgs[index]+'")';$('.next').style.backgroundImage='url("'+imgs[(index+1)%imgs.length]+'")';$('.prev').style.backgroundImage='url("'+imgs[(index-1+imgs.length)%imgs.length]+'")';$('#index').textContent=String(index+1).padStart(2,'0')}
function release(){if(Math.abs(target)>innerWidth*.16){const dir=target<0?1:-1;current=target<0?-innerWidth:innerWidth;setSlides(dir);setTimeout(()=>{current=0;target=0},120)}else target=0}
function begin(x){startX=x;tracking=true;$('#gesture').textContent='TRACKING'}
function move(x){if(tracking)target=Math.max(-innerWidth*.85,Math.min(innerWidth*.85,x-startX))}
function end(){if(tracking){tracking=false;release();$('#gesture').textContent='IDLE'}}
addEventListener('resize',resize);addEventListener('pointerdown',e=>begin(e.clientX));addEventListener('pointermove',e=>move(e.clientX));addEventListener('pointerup',end);
function draw(){current+=(target-current)*.14;root.style.setProperty('--x',current+'px');root.style.setProperty('--p',Math.min(1,Math.abs(current)/innerWidth));ctx.clearRect(0,0,w,h);for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.x+=p.vx;p.y+=p.vy;p.life-=.035;ctx.fillStyle='rgba(233,227,213,'+(p.life*.35)+')';ctx.fillRect(p.x,p.y,2,2);if(p.life<=0)particles.splice(i,1)}requestAnimationFrame(draw)}
async function camera(){const b=$('#cameraBtn'),g=$('#gesture');b.disabled=true;b.textContent='请求摄像头权限...';g.textContent='REQUESTING CAMERA';try{if(!navigator.mediaDevices||!navigator.mediaDevices.getUserMedia)throw new Error('此浏览器不支持摄像头');video.srcObject=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:640,height:480},audio:false});await video.play();document.body.classList.add('camera-on');$('#mode').textContent='CAMERA MODE';b.textContent='摄像头已启用';g.textContent='加载手势模型';const m=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/+esm');const files=await m.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');landmarker=await m.HandLandmarker.createFromOptions(files,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/hand_landmarker/hand_landmarker/float16/1/hand_landmarker.task',delegate:'GPU'},runningMode:'VIDEO',numHands:1});g.textContent='把手放到镜头前';handLoop()}catch(e){console.error(e);b.disabled=false;b.textContent='重试摄像头';g.textContent='摄像头失败: '+(e.name||e.message);$('#mode').textContent='POINTER FALLBACK'}}
function handLoop(){if(landmarker&&video.readyState>=2){const r=landmarker.detectForVideo(video,performance.now());if(r.landmarks&&r.landmarks[0]){const x=(1-r.landmarks[0][9].x)*innerWidth;if(!tracking)begin(x);move(x)}else end()}requestAnimationFrame(handLoop)}
$('#cameraBtn').addEventListener('click',e=>{e.stopPropagation();camera()});
resize();draw();